language: ruby

before_install:
  - gem update --system 2.6.14
  - gem --version

script: make test

rvm:
  - 2.2.2
  - 2.3.3
  - 2.4.1
  - jruby-9.1.15.0
  - rbx-3

gemfile: ".travis/Gemfile"

sudo: false

before_script:
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1
  matrix:
    - DRIVER=ruby      REDIS_BRANCH=3.0
    - DRIVER=ruby      REDIS_BRANCH=3.2
    - DRIVER=hiredis   REDIS_BRANCH=3.0
    - DRIVER=hiredis   REDIS_BRANCH=3.2
    - DRIVER=synchrony REDIS_BRANCH=3.0
    - DRIVER=synchrony REDIS_BRANCH=3.2
    - DRIVER=ruby      REDIS_BRANCH=unstable

branches:
  only:
    - staging
    - trying
    - master

matrix:
  exclude:
    # hiredis
    - rvm: jruby-9.1.15.0
      gemfile: .travis/Gemfile
      env: DRIVER=hiredis REDIS_BRANCH=3.0
    - rvm: jruby-9.1.15.0
      gemfile: .travis/Gemfile
      env: DRIVER=hiredis REDIS_BRANCH=3.2
    - rvm: jruby-9.1.15.0
      gemfile: .travis/Gemfile
      env: DRIVER=hiredis REDIS_BRANCH=3.0
    - rvm: jruby-9.1.15.0
      gemfile: .travis/Gemfile
      env: DRIVER=hiredis REDIS_BRANCH=3.2

    # synchrony
    - rvm: jruby-9.1.15.0
      gemfile: .travis/Gemfile
      env: DRIVER=synchrony REDIS_BRANCH=3.0
    - rvm: jruby-9.1.15.0
      gemfile: .travis/Gemfile
      env: DRIVER=synchrony REDIS_BRANCH=3.2
    - rvm: jruby-9.1.15.0
      gemfile: .travis/Gemfile
      env: DRIVER=synchrony REDIS_BRANCH=3.0
    - rvm: jruby-9.1.15.0
      gemfile: .travis/Gemfile
      env: DRIVER=synchrony REDIS_BRANCH=3.2
  allow_failures:
    - rvm: rbx-3

notifications:
  irc:
    - irc.freenode.net#redis-rb
  email: false
