language: ruby
cache:
    directories:
      - tmp/cache
before_install:
  - gem update --system 3.0.3
  - gem --version

script: make

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - jruby-9.1.17.0

sudo: false

before_script:
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT

env:
  global:
    - VERBOSE=true
    - TIMEOUT=30
    - LOW_TIMEOUT=0.01
  matrix:
    - DRIVER=ruby      REDIS_BRANCH=5.0
    - DRIVER=hiredis   REDIS_BRANCH=5.0
    - DRIVER=synchrony REDIS_BRANCH=5.0

branches:
  only:
    - staging
    - trying
    - master

matrix:
  exclude:
    - rvm: jruby-9.1.17.0
  include:
    - rvm: jruby-9.1.17.0
      env: DRIVER=ruby REDIS_BRANCH=5.0 LOW_TIMEOUT=0.3
    - rvm: 2.3.8
      env: DRIVER=ruby REDIS_BRANCH=3.0
    - rvm: 2.3.8
      env: DRIVER=ruby REDIS_BRANCH=3.2
    - rvm: 2.3.8
      env: DRIVER=ruby REDIS_BRANCH=4.0

notifications:
  irc:
    - irc.freenode.net#redis-rb
  email: false
